#!/usr/bin/env bash

echo "🎨 Checking formatting..."
pnpm run format:check

echo "💡 TS-Check..."
pnpm run ts-check

echo "✄ Running knip"
pnpm run knip

echo "🏁 Astro check..."
pnpm run astro-check

echo "🏗️ Checking build for errors..."
pnpm run build
